version: '3'

services:
  postgres-db:
    container_name: euripedes-bd
    image: 'bitnami/postgresql:16.6.0'
    env_file:
      - ../../.env.development
    ports:
      - 5432:5432
    volumes:
      - ../../data/pg:/data/postgres
