name: run-all-tests-e2e

on:
  workflow_run:
    workflows: [Run-all-tests-unit-CI]
    types:
      - completed

jobs:
  run-all-tests-e2e:
    name: Run all tests e2e
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install nodejs(version lts)
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'

      - name: install dependency
        run: npm ci

      - name: install docker compose
        uses: docker/setup-compose-action@v1

      - name: Run services docker compose
        run: docker compose -f src/infra/docker-compose.yaml up -d

      - name: run tests e2e
        run: npm run test:e2e
